### PR TITLE
Linux script can now read from setting file

### PR DESCRIPTION
**Pull request by Dijkstra1-zz**
Do your worst @OrdinatorStouff

### CODE REVIEW

**Comment by OrdinatorStouff** [comment]
Are you echoing to the stdout to then reading the string in from stdout? If so that seems messy. Also why is the last commented line needed?

**Comment by Dijkstra1-zz** [comment]
the last was being read
and nothing is being printed to the console

**Comment by OrdinatorStouff** [comment]
what about
`while read -r line || [[ -n "$line" ]] ; do`

**Comment by Dijkstra1-zz** [comment]
c you know about this stuff then me, works last can go

**Comment by OrdinatorStouff** [comment]
I just google well.

I don't want to merge yet until I have the windows version also reading from the same config so both scripts are consistent.

**Comment by Dijkstra1-zz** [comment]
that's fine we should make an working branch that we can both commit and merge when the time comes

**Comment by OrdinatorStouff** [comment]
Closing PR since scripts are now handled on the team repo https://github.com/AllTheMods/Server-Scripts/

**Pull request closed without merging**
